### ISSUE TITLE
SyntaxError: f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by pzdc-pixel** [Keqy/telegram-parser-v2.0#5]
(venv) D:\TELEGRAM_MANIAC\telegram-parser-v2.0-RUS-main\telegram-parser-v2.0-RUS-main>py main.py
Traceback (most recent call last):
  File "D:\TELEGRAM_MANIAC\telegram-parser-v2.0-RUS-main\telegram-parser-v2.0-RUS-main\main.py", line 5, in <module>
    from defunc import *
  File "D:\TELEGRAM_MANIAC\telegram-parser-v2.0-RUS-main\telegram-parser-v2.0-RUS-main\defunc.py", line 63
    "Ввод: ")
            ^
SyntaxError: f-string expression part cannot include a backslash

**Comment by Keqy** [comment]
Обновите Python до >= 3.12
